# Generated by Django 6.1 on 2026-08-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='learning_skills',
            field=models.ManyToManyField(blank=True, related_name='learners', to='skill_management.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_skills',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='skill_management.skill'),
        ),
    ]
