# Generated by Django 6.1 on 2026-08-27 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef'), ('codeforces', 'Codeforces'), ('hackerrank', 'HackerRank'), ('behance', 'Behance'), ('website', 'Personal Website'), ('other', 'Other')], max_length=30)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('profile_url', models.URLField(blank=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_profiles', to='user_management.userprofile')),
            ],
        ),
    ]
