# Generated by Django 6.1 on 2026-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_connectedprofile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connectedprofile',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform'),
        ),
    ]
