# Generated by Django 6.1 on 2026-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_connectedprofile_unique_user_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectedprofile',
            options={'ordering': ['category', 'platform']},
        ),
        migrations.AddField(
            model_name='connectedprofile',
            name='category',
            field=models.CharField(choices=[('professional', 'Professional'), ('coding', 'Coding'), ('creative', 'Creative'), ('social', 'Social'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='connectedprofile',
            name='profile_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='connectedprofile',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('leetcode', 'LeetCode'), ('codechef', 'CodeChef'), ('codeforces', 'Codeforces'), ('hackerrank', 'HackerRank'), ('behance', 'Behance'), ('website', 'Personal Website'), ('instagram', 'Instagram'), ('twitter', 'X / Twitter'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('threads', 'Threads'), ('other', 'Other')], max_length=30),
        ),
    ]
