# Generated by Django 6.1 on 2026-09-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation_pair',
        ),
    ]
