# Generated by Django 6.1 on 2026-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_management', '0002_remove_conversation_unique_conversation_pair'),
        ('user_management', '0006_alter_connectedprofile_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_one', 'participant_two'), name='unique_conversation_pair'),
        ),
    ]
