# Generated by Django 6.1 on 2026-08-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skillexchangerequest',
            name='unique_skill_exchange_request',
        ),
    ]
